import { Html, Head, Main, NextScript } from 'next/document';

export const metadata = {
  title: 'Govt. Schemes',
  // description: 'Generated by create next app',
}

export default function Document({ children }) {
  return (

    <Html lang="en">
      <Head />
      <body className={'font-gilroy font-medium text-gray text-lg leading-[27px]'}>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
