import './globals.css';
import ClientRoot from './ClientRoot';

export const metadata = {
  title: 'Govt. Schemes',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'font-gilroy font-medium text-gray text-lg leading-[27px]'}>
        <ClientRoot>{children}</ClientRoot>
      </body>
    </html>
  )
}
